### ISSUE TITLE
No signature of private method applyDefaultConfiguration() visible in clousure

### ISSUE THREAD

**Issue by vudzkostek** [heremaps/gradle-jenkins-jobdsl-plugin#117]
I get:
 javaposse.jobdsl.dsl.DslScriptException: (PipelineBuilder.groovy, line 71) No signature of method: package.HourlyPipelineBuilder.applyDefaultConfiguration() is applicable for argument types: (package.TriggerJobBuilder) values: [package.TriggerJobBuilder@7584ddc1]

HourlyPipelineBuilder extends com.here.gradle.plugins.jobdsl.util.PipelineBuilder
TriggerJobBuilder extends com.here.gradle.plugins.jobdsl.util.PipelineJobBuilder

applyDefaultConfiguration is a private method in PipelineBuilder but it is called from clousure in build() and I think this is an issue related to these bugs in groovy:
https://issues.apache.org/jira/browse/GROOVY-3073
https://issues.apache.org/jira/browse/GROOVY-3010

I would change signature of method to 'protected final' but I am not an expert

**Comment by mnonnenmacher** [comment]
Your fix is part of 3.5.0 which was just released.

**Comment by vudzkostek** [comment]
Great! thank you
