### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by sschuberth** [heremaps/gradle-jenkins-jobdsl-plugin#35]
For once, "jobdsl" seems to be more common than "job-dsl" (although I agree the latter is slight better to read). Secondly, I believe it would be nice to somehow express the relationship to Jenkins in the name. Maybe "gradle-jenkins-dsl-plugin"?

**Comment by mnonnenmacher** [comment]
I would go for "gradle-jenkins-jobdsl-plugin" instead to avoid confusion with the Pipeline DSL, do you agree?

**Comment by sschuberth** [comment]
Agreed. "gradle-jenkins-jobdsl-plugin" also was on my list of proposals, but I though you'd find it to be too long 😉

**Comment by mnonnenmacher** [comment]
Renamed the repository already.
