### ISSUE TITLE
add the custom dsl plugin 

### ISSUE THREAD

**Issue by jiahut** [heremaps/gradle-jenkins-jobdsl-plugin#58]
when add the custom plugin 

like ：

  ` compile group: 'org.jenkins-ci.plugins', name: 'jgiven', version: '0.15.1'`

but  it report 

`No signature of method: javaposse.jobdsl.dsl.helpers.publisher.PublisherContext.jgivenReports()`

How does  it to do with add the custom plugin ?

**Comment by mnonnenmacher** [comment]
Hi @jiahut, the jgiven plugin provides its own extension for JobDSL. Currently this is not supported by this Gradle plugin, but it will be once https://github.com/heremaps/gradle-jenkins-jobdsl-plugin/issues/12 is implemented which I am actively working on. Please subscribe to this ticket for further updates.

**Comment by jiahut** [comment]
@mnonnenmacher thanks a lot

**Comment by mnonnenmacher** [comment]
Hi @jiahut , I have released version 3.0.0 which now supports extensions, could you give it a try and check if it works for you? The readme and example project have also been updated.

**Comment by jiahut** [comment]
@mnonnenmacher good job.  it works well.
