### ISSUE TITLE
the pipelineBuilder defaultConfiguration overwrite the job specify key

### ISSUE THREAD

**Issue by jiahut** [heremaps/gradle-jenkins-jobdsl-plugin#63]
for example: 
```
def pipelineBuilder = new PipelineBuilder()
pipelineBuilder.with {
defaultConfiguration([
      javaHome: "/usr/local/jdk1.7.0_71"
])}

def checkJob = new CheckJobBuilder(this)
checkJob.with {
    javaHome = "/usr/local/jdk1.8.0_151"
}
pipelineBuilder.with{
    addJob(checkJob)
    build()
}
```

we expect the `checkJob`' s `javaHome` is `/usr/local/jdk1.8.0_151`
but actually the `checkJob`' s `javaHome` is `/usr/local/jdk1.7.0_71`
the `pipelineBuilder` `defaultConfiguration` overwrite the job specify key.

the following is the source of `defaultConfiguration`
https://github.com/heremaps/gradle-jenkins-jobdsl-plugin/blob/2de8e07640b0949e178afc534180c78341f4decd/plugin/src/main/groovy/com/here/gradle/plugins/jobdsl/util/PipelineBuilder.groovy#L59-L62

can filter the key which the jobs had specified . 

@mnonnenmacher 
 
thinks

**Comment by mnonnenmacher** [comment]
Thanks for the report @jiahut, the fix will be in 3.0.0 which will be released soon.
